--// ════════════════════════════════════════════════════════════════
--// YinYang_Stickers.lua — Archivo externo de stickers
--// Subir a: https://github.com/Yinyangzx/Yin-Stickers
--// La librería descarga este archivo automáticamente.
--// Para agregar stickers: agregar entrada en Stickers + nombre en Order.
--//
--// ⚠️ REGLA IMPORTANTE: Los KEYS de la tabla Stickers (y los nombres
--// en Order) deben ser ASCII puro, sin tildes ni caracteres especiales.
--// Los labels de display (LabelES, LabelEN) SÍ pueden tener tildes.
--// ════════════════════════════════════════════════════════════════

return {
    Version = 2,

    -- Orden en que aparecen los stickers en la UI
    Order = {
        "Sonrisa",
        "Llorar",
        "Amor",
        "Corazon",
        "Emoji",
        "Risa",
        "Sorpresa",
        "Triste",
        "Enojado",
        "Wink",
        "Cool",
        "Fuego",
        "Explosion",
        "Trueno",
        "Magico",
        "Bruja",
        "Fantasma",
        "Calavera",
        "Demonio",
        "Emoji2",
        "Emoji3",
        "Emoji4",
        "Emoji5",
        "Emoji6",
        "Emoji7",
        "Emoji8",
        "Emoji9",
        "Emoji10",
        "Emoji11",
        "Emoji12",
        "Emoji13",
        "Emoji14",
        "Emoji15",
        "Emoji16",
        "Emoji17",
        "Emoji18",
        "Emoji19",
        "Emoji20",
        "Chispa",
        "Aurora",
        "Nebula",
        "Cometa",
        "Viento",
        "Tormenta",
        "Nieve",
        "Lluvia",
        "Arcoiris",
        "Cristal",
        "Volcan",
        "Selva",
        "Oceano",
        "Desierto",
        "Montana",
        "Glaciar",
        "Cascada",
        "Ceniza",
        "Rayo",
        "Humo",
        "Espejo",
        "Sombra",
        "Eclipse",
        "Galaxia",
        "Meteoro",
        "Cosmos",
        "Lunar",
        "Solar",
        "Estrella",
        "Planeta",
        "Polvo",
        "Niebla",
        "Escarcha",
        "Bruma",
        "Tifon",
        "Ciclon",
        "Vendaval",
        "Granizo",
        "Relampago",
        "Tsunami",
        "Terremoto",
        "Lava",
        "Crater",
        "Grieta",
        "Abismo",
        "Coral",
        "Perla",
        "Alga",
        "Medusa",
        "Pulpo",
        "Ballena",
        "Tiburon",
        "Delfin",
        "Tortuga",
        "Cangrejo",
        "Pez",
        "Sirena",
        "Kraken",
        "Ancla",
        "Barco",
        "Faro",
        "Ola",
        "Concha",
        "Buzo",
        "Tesoro",
        "Pirata",
        "Brujula",
        "Mapa",
        "Espada",
        "Escudo",
        "Corona",
        "Gema",
        "Amuleto",
        "Pergamino",
        "Pocion",
        "Varita",
        "Hechizo",
        "Dragon",
        "Fenix",
        "Unicornio",
        "Grifo",
        "Basilisco",
        "Hidra",
        "Golem",
        "Espectro",
        "Vampiro",
        "Lobo",
        "Cuervo",
        "Serpiente",
        "Arana",
        "Murcielago",
        "Sapo",
        "Pino",
        "Roble",
        "Bambu",
        "Cactus",
        "Hongo",
        "Flor",
        "Rosa",
        "Girasol",
        "Lirio",
        "Trebol",
        "Hoja",
        "Semilla",
        "Raiz",
        "Fruto",
        "Manzana",
        "Limon",
        "Cereza",
        "Uva",
        "Sandia",
        "Pera",
        "Durazno",
        "Platano",
        "Coco",
        "Pina",
        "Fresa",
        "Zanahoria",
        "Maiz",
        "Calabaza",
        "Berenjena",
        "Chile",
        "Brocoli",
        "Lechuga",
        "Tomate",
        "Pepino",
        "Aguacate",
        "Lirio2",
        "Jazmin",
        "Perro",
        "Gato",
        "Conejo",
        "Hamster",
        "Raton",
        "Ardilla",
        "Zorro",
        "Oso",
        "Panda",
        "Koala",
        "Canguro",
        "Elefante",
        "Jirafa",
        "Cebra",
        "Leon",
        "Tigre",
        "Leopardo",
        "Hipopotamo",
        "Rinoceronte",
        "Gorila",
        "Mono",
        "Pinguino",
        "Buho",
        "Aguila",
        "Loro",
        "Flamenco",
        "Pavo",
        "Paloma",
        "Colibri",
        "Pelicano",
        "Cocodrilo",
        "Iguana",
        "Camaleon",
        "Gecko",
        "Rana",
        "Axolotl",
        "Caballo",
        "Burro",
        "Vaca",
        "Toro",
        "Oveja",
        "Cabra",
        "Cerdo",
        "Gallina",
        "Gallo",
        "Pato",
        "Ganso",
        "Camello",
        "Llama",
        "Alpaca",
        "Ciervo",
        "Alce",
        "Bisonte",
        "Nutria",
        "Castor",
        "Mapache",
        "Mofeta",
        "Coyote",
        "Hiena",
        "Suricata",
        "Wombat",
        "Tapir",
        "Capibara",
        "Armadillo",
        "Topo",
        "Erizo",
        "Muflon",
        "Bufalo",
        "Antilope",
        "Ornitorrinco",
        "Puercoespin",
        "Mangosta",
        "Turon",
        "Huron",
        "Civeta",
        "Binturong",
    },

    -- Datos de cada sticker
    Stickers = {
        Sonrisa = {
            Image   = "rbxassetid://135857695171095",
            LabelES = "Sonrisa",
            LabelEN = "Smile",
        },
        Llorar = {
            Image   = "rbxassetid://138363247925206",
            LabelES = "Llorar",
            LabelEN = "Crying",
        },
        Amor = {
            Image   = "rbxassetid://76164124882568",
            LabelES = "Amor",
            LabelEN = "Love",
        },
        Corazon = {
            Image   = "rbxassetid://76164124882568",
            LabelES = "Corazón",
            LabelEN = "Heart",
        },
        Emoji = {
            Image   = "rbxassetid://133861773375312",
            LabelES = "Emoji",
            LabelEN = "Emoji",
        },
        Risa = {
            Image   = "rbxassetid://109165098870367",
            LabelES = "Risa",
            LabelEN = "Laugh",
        },
        Sorpresa = {
            Image   = "rbxassetid://89213081637073",
            LabelES = "Sorpresa",
            LabelEN = "Surprised",
        },
        Triste = {
            Image   = "rbxassetid://80817302481160",
            LabelES = "Triste",
            LabelEN = "Sad",
        },
        Enojado = {
            Image   = "rbxassetid://72815688632249",
            LabelES = "Enojado",
            LabelEN = "Angry",
        },
        Wink = {
            Image   = "rbxassetid://72602706593283",
            LabelES = "Guiño",
            LabelEN = "Wink",
        },
        Cool = {
            Image   = "rbxassetid://129224642026377",
            LabelES = "Cool",
            LabelEN = "Cool",
        },
        Fuego = {
            Image   = "rbxassetid://110399103599356",
            LabelES = "Fuego",
            LabelEN = "Fire",
        },
        Explosion = {                          -- ← key sin tilde
            Image   = "rbxassetid://92508415428532",
            LabelES = "Explosión",             -- ← label SÍ puede tener tilde
            LabelEN = "Explosion",
        },
        Trueno = {
            Image   = "rbxassetid://116834306902804",
            LabelES = "Trueno",
            LabelEN = "Thunder",
        },
        Magico = {                             -- ← key sin tilde
            Image   = "rbxassetid://88512827318318",
            LabelES = "Mágico",               -- ← label SÍ puede tener tilde
            LabelEN = "Magic",
        },
        Bruja = {
            Image   = "rbxassetid://104843488715259",
            LabelES = "Bruja",
            LabelEN = "Witch",
        },
        Fantasma = {
            Image   = "rbxassetid://120595244684744",
            LabelES = "Fantasma",
            LabelEN = "Ghost",
        },
        Calavera = {
            Image   = "rbxassetid://136019522994141",
            LabelES = "Calavera",
            LabelEN = "Skull",
        },
        Demonio = {
            Image   = "rbxassetid://92086956614552",
            LabelES = "Demonio",
            LabelEN = "Demon",
        },
        Emoji2 = {
            Image   = "rbxassetid://137126758667284",
            LabelES = "Emoji2",
            LabelEN = "Emoji2",
        },
        Emoji3 = {
            Image   = "rbxassetid://100678993930995",
            LabelES = "Emoji3",
            LabelEN = "Emoji3",
        },
        Emoji4 = {
            Image   = "rbxassetid://100345922509049",
            LabelES = "Emoji4",
            LabelEN = "Emoji4",
        },
        Emoji5 = {
            Image   = "rbxassetid://112758471473211",
            LabelES = "Emoji5",
            LabelEN = "Emoji5",
        },
        Emoji6 = {
            Image   = "rbxassetid://118210800680043",
            LabelES = "Emoji6",
            LabelEN = "Emoji6",
        },
        Emoji7 = {
            Image   = "rbxassetid://104930670798953",
            LabelES = "Emoji7",
            LabelEN = "Emoji7",
        },
        Emoji8 = {
            Image   = "rbxassetid://111086994425425",
            LabelES = "Emoji8",
            LabelEN = "Emoji8",
        },
        Emoji9 = {
            Image   = "rbxassetid://98302768923536",
            LabelES = "Emoji9",
            LabelEN = "Emoji9",
        },
        Emoji10 = {
            Image   = "rbxassetid://85952272922609",
            LabelES = "Emoji10",
            LabelEN = "Emoji10",
        },
        Emoji11 = {
            Image   = "rbxassetid://95705887311474",
            LabelES = "Emoji11",
            LabelEN = "Emoji11",
        },
        Emoji12 = {
            Image   = "rbxassetid://135929327239841",
            LabelES = "Emoji12",
            LabelEN = "Emoji12",
        },
        Emoji13 = {
            Image   = "rbxassetid://103525376091448",
            LabelES = "Emoji13",
            LabelEN = "Emoji13",
        },
        Emoji14 = {
            Image   = "rbxassetid://88295400480520",
            LabelES = "Emoji14",
            LabelEN = "Emoji14",
        },
        Emoji15 = {
            Image   = "rbxassetid://125415121021604",
            LabelES = "Emoji15",
            LabelEN = "Emoji15",
        },
        Emoji16 = {
            Image   = "rbxassetid://103005450871974",
            LabelES = "Emoji16",
            LabelEN = "Emoji16",
        },
        Emoji17 = {
            Image   = "rbxassetid://104843034307695",
            LabelES = "Emoji17",
            LabelEN = "Emoji17",
        },
        Emoji18 = {
            Image   = "rbxassetid://70369002557517",
            LabelES = "Emoji18",
            LabelEN = "Emoji18",
        },
        Emoji19 = {
            Image   = "rbxassetid://114826712564965",
            LabelES = "Emoji19",
            LabelEN = "Emoji19",
        },
        Emoji20 = {
            Image   = "rbxassetid://94598866267972",
            LabelES = "Emoji20",
            LabelEN = "Emoji20",
        },
        Chispa = {
            Image   = "rbxassetid://95581850042375",
            LabelES = "Chispa",
            LabelEN = "Spark",
        },
        Aurora = {
            Image   = "rbxassetid://95803999841395",
            LabelES = "Aurora",
            LabelEN = "Aurora",
        },
        Nebula = {
            Image   = "rbxassetid://92718677126013",
            LabelES = "Nebulosa",
            LabelEN = "Nebula",
        },
        Cometa = {
            Image   = "rbxassetid://79872700399912",
            LabelES = "Cometa",
            LabelEN = "Comet",
        },
        Viento = {
            Image   = "rbxassetid://117133097283928",
            LabelES = "Viento",
            LabelEN = "Wind",
        },
        Tormenta = {
            Image   = "rbxassetid://111428536689397",
            LabelES = "Tormenta",
            LabelEN = "Storm",
        },
        Nieve = {
            Image   = "rbxassetid://76945251946009",
            LabelES = "Nieve",
            LabelEN = "Snow",
        },
        Lluvia = {
            Image   = "rbxassetid://133799788243573",
            LabelES = "Lluvia",
            LabelEN = "Rain",
        },
        Arcoiris = {
            Image   = "rbxassetid://116537247539117",
            LabelES = "Arcoíris",
            LabelEN = "Rainbow",
        },
        Cristal = {
            Image   = "rbxassetid://123074789751366",
            LabelES = "Cristal",
            LabelEN = "Crystal",
        },
        Volcan = {
            Image   = "rbxassetid://103401059843279",
            LabelES = "Volcán",
            LabelEN = "Volcano",
        },
        Selva = {
            Image   = "rbxassetid://120526367481996",
            LabelES = "Selva",
            LabelEN = "Jungle",
        },
        Oceano = {
            Image   = "rbxassetid://128904016042681",
            LabelES = "Océano",
            LabelEN = "Ocean",
        },
        Desierto = {
            Image   = "rbxassetid://125214865577344",
            LabelES = "Desierto",
            LabelEN = "Desert",
        },
        Montana = {
            Image   = "rbxassetid://94217246525251",
            LabelES = "Montaña",
            LabelEN = "Mountain",
        },
        Glaciar = {
            Image   = "rbxassetid://121327271135938",
            LabelES = "Glaciar",
            LabelEN = "Glacier",
        },
        Cascada = {
            Image   = "rbxassetid://96203420524449",
            LabelES = "Cascada",
            LabelEN = "Waterfall",
        },
        Ceniza = {
            Image   = "rbxassetid://92306099016836",
            LabelES = "Ceniza",
            LabelEN = "Ash",
        },
        Rayo = {
            Image   = "rbxassetid://113155678479800",
            LabelES = "Rayo",
            LabelEN = "Lightning",
        },
        Humo = {
            Image   = "rbxassetid://95045299546526",
            LabelES = "Humo",
            LabelEN = "Smoke",
        },
        Espejo = {
            Image   = "rbxassetid://120501907234593",
            LabelES = "Espejo",
            LabelEN = "Mirror",
        },
        Sombra = {
            Image   = "rbxassetid://123994460997589",
            LabelES = "Sombra",
            LabelEN = "Shadow",
        },
        Eclipse = {
            Image   = "rbxassetid://90153211786295",
            LabelES = "Eclipse",
            LabelEN = "Eclipse",
        },
        Galaxia = {
            Image   = "rbxassetid://80126163727707",
            LabelES = "Galaxia",
            LabelEN = "Galaxy",
        },
        Meteoro = {
            Image   = "rbxassetid://133168900745789",
            LabelES = "Meteoro",
            LabelEN = "Meteor",
        },
        Cosmos = {
            Image   = "rbxassetid://94279972259287",
            LabelES = "Cosmos",
            LabelEN = "Cosmos",
        },
        Lunar = {
            Image   = "rbxassetid://140299752034763",
            LabelES = "Lunar",
            LabelEN = "Lunar",
        },
        Solar = {
            Image   = "rbxassetid://93100568726756",
            LabelES = "Solar",
            LabelEN = "Solar",
        },
        Estrella = {
            Image   = "rbxassetid://95102274532516",
            LabelES = "Estrella",
            LabelEN = "Star",
        },
        Planeta = {
            Image   = "rbxassetid://117010359725523",
            LabelES = "Planeta",
            LabelEN = "Planet",
        },
        Polvo = {
            Image   = "rbxassetid://132413821451425",
            LabelES = "Polvo",
            LabelEN = "Dust",
        },
        Niebla = {
            Image   = "rbxassetid://127594655993153",
            LabelES = "Niebla",
            LabelEN = "Fog",
        },
        Escarcha = {
            Image   = "rbxassetid://111544924668026",
            LabelES = "Escarcha",
            LabelEN = "Frost",
        },
        Bruma = {
            Image   = "rbxassetid://82124174654502",
            LabelES = "Bruma",
            LabelEN = "Mist",
        },
        Tifon = {
            Image   = "rbxassetid://116639353407925",
            LabelES = "Tifón",
            LabelEN = "Typhoon",
        },
        Ciclon = {
            Image   = "rbxassetid://89986068255808",
            LabelES = "Ciclón",
            LabelEN = "Cyclone",
        },
        Vendaval = {
            Image   = "rbxassetid://139663371147887",
            LabelES = "Vendaval",
            LabelEN = "Gale",
        },
        Granizo = {
            Image   = "rbxassetid://119621445631729",
            LabelES = "Granizo",
            LabelEN = "Hail",
        },
        Relampago = {
            Image   = "rbxassetid://117554925451123",
            LabelES = "Relámpago",
            LabelEN = "Lightning2",
        },
        Tsunami = {
            Image   = "rbxassetid://80967751295659",
            LabelES = "Tsunami",
            LabelEN = "Tsunami",
        },
        Terremoto = {
            Image   = "rbxassetid://81569110061714",
            LabelES = "Terremoto",
            LabelEN = "Earthquake",
        },
        Lava = {
            Image   = "rbxassetid://78620374257610",
            LabelES = "Lava",
            LabelEN = "Lava",
        },
        Crater = {
            Image   = "rbxassetid://94231172665532",
            LabelES = "Cráter",
            LabelEN = "Crater",
        },
        Grieta = {
            Image   = "rbxassetid://80021490859398",
            LabelES = "Grieta",
            LabelEN = "Crack",
        },
        Abismo = {
            Image   = "rbxassetid://131756849867286",
            LabelES = "Abismo",
            LabelEN = "Abyss",
        },
        Coral = {
            Image   = "rbxassetid://99157547595885",
            LabelES = "Coral",
            LabelEN = "Coral",
        },
        Perla = {
            Image   = "rbxassetid://119304782494852",
            LabelES = "Perla",
            LabelEN = "Pearl",
        },
        Alga = {
            Image   = "rbxassetid://116975816945061",
            LabelES = "Alga",
            LabelEN = "Seaweed",
        },
        Medusa = {
            Image   = "rbxassetid://77106317240160",
            LabelES = "Medusa",
            LabelEN = "Jellyfish",
        },
        Pulpo = {
            Image   = "rbxassetid://115829010355316",
            LabelES = "Pulpo",
            LabelEN = "Octopus",
        },
        Ballena = {
            Image   = "rbxassetid://137688735715140",
            LabelES = "Ballena",
            LabelEN = "Whale",
        },
        Tiburon = {
            Image   = "rbxassetid://116409512403131",
            LabelES = "Tiburón",
            LabelEN = "Shark",
        },
        Delfin = {
            Image   = "rbxassetid://99053216881022",
            LabelES = "Delfín",
            LabelEN = "Dolphin",
        },
        Tortuga = {
            Image   = "rbxassetid://137182944732292",
            LabelES = "Tortuga",
            LabelEN = "Turtle",
        },
        Cangrejo = {
            Image   = "rbxassetid://115253180116055",
            LabelES = "Cangrejo",
            LabelEN = "Crab",
        },
        Pez = {
            Image   = "rbxassetid://118840750645763",
            LabelES = "Pez",
            LabelEN = "Fish",
        },
        Sirena = {
            Image   = "rbxassetid://133951487868459",
            LabelES = "Sirena",
            LabelEN = "Mermaid",
        },
        Kraken = {
            Image   = "rbxassetid://89882760849068",
            LabelES = "Kraken",
            LabelEN = "Kraken",
        },
        Ancla = {
            Image   = "rbxassetid://93110963106567",
            LabelES = "Ancla",
            LabelEN = "Anchor",
        },
        Barco = {
            Image   = "rbxassetid://94590392484140",
            LabelES = "Barco",
            LabelEN = "Ship",
        },
        Faro = {
            Image   = "rbxassetid://79210560933345",
            LabelES = "Faro",
            LabelEN = "Lighthouse",
        },
        Ola = {
            Image   = "rbxassetid://119192566313652",
            LabelES = "Ola",
            LabelEN = "Wave",
        },
        Concha = {
            Image   = "rbxassetid://82200252339063",
            LabelES = "Concha",
            LabelEN = "Shell",
        },
        Buzo = {
            Image   = "rbxassetid://122653076568798",
            LabelES = "Buzo",
            LabelEN = "Diver",
        },
        Tesoro = {
            Image   = "rbxassetid://83200483547045",
            LabelES = "Tesoro",
            LabelEN = "Treasure",
        },
        Pirata = {
            Image   = "rbxassetid://76141479009493",
            LabelES = "Pirata",
            LabelEN = "Pirate",
        },
        Brujula = {
            Image   = "rbxassetid://140555567993609",
            LabelES = "Brújula",
            LabelEN = "Compass",
        },
        Mapa = {
            Image   = "rbxassetid://131280050731169",
            LabelES = "Mapa",
            LabelEN = "Map",
        },
        Espada = {
            Image   = "rbxassetid://117082090085435",
            LabelES = "Espada",
            LabelEN = "Sword",
        },
        Escudo = {
            Image   = "rbxassetid://121144896816993",
            LabelES = "Escudo",
            LabelEN = "Shield",
        },
        Corona = {
            Image   = "rbxassetid://140445635024612",
            LabelES = "Corona",
            LabelEN = "Crown",
        },
        Gema = {
            Image   = "rbxassetid://82828843090079",
            LabelES = "Gema",
            LabelEN = "Gem",
        },
        Amuleto = {
            Image   = "rbxassetid://113751369820338",
            LabelES = "Amuleto",
            LabelEN = "Amulet",
        },
        Pergamino = {
            Image   = "rbxassetid://86464399042450",
            LabelES = "Pergamino",
            LabelEN = "Scroll",
        },
        Pocion = {
            Image   = "rbxassetid://125240157452012",
            LabelES = "Poción",
            LabelEN = "Potion",
        },
        Varita = {
            Image   = "rbxassetid://140085951058090",
            LabelES = "Varita",
            LabelEN = "Wand",
        },
        Hechizo = {
            Image   = "rbxassetid://138320135894842",
            LabelES = "Hechizo",
            LabelEN = "Spell",
        },
        Dragon = {
            Image   = "rbxassetid://122205335787901",
            LabelES = "Dragón",
            LabelEN = "Dragon",
        },
        Fenix = {
            Image   = "rbxassetid://127087782006997",
            LabelES = "Fénix",
            LabelEN = "Phoenix",
        },
        Unicornio = {
            Image   = "rbxassetid://108469400934757",
            LabelES = "Unicornio",
            LabelEN = "Unicorn",
        },
        Grifo = {
            Image   = "rbxassetid://136054862106729",
            LabelES = "Grifo",
            LabelEN = "Griffin",
        },
        Basilisco = {
            Image   = "rbxassetid://115997732319845",
            LabelES = "Basilisco",
            LabelEN = "Basilisk",
        },
        Hidra = {
            Image   = "rbxassetid://137002653147439",
            LabelES = "Hidra",
            LabelEN = "Hydra",
        },
        Golem = {
            Image   = "rbxassetid://104935956981983",
            LabelES = "Golem",
            LabelEN = "Golem",
        },
        Espectro = {
            Image   = "rbxassetid://98240306130641",
            LabelES = "Espectro",
            LabelEN = "Specter",
        },
        Vampiro = {
            Image   = "rbxassetid://124118525296155",
            LabelES = "Vampiro",
            LabelEN = "Vampire",
        },
        Lobo = {
            Image   = "rbxassetid://92115180165013",
            LabelES = "Lobo",
            LabelEN = "Wolf",
        },
        Cuervo = {
            Image   = "rbxassetid://93406057361068",
            LabelES = "Cuervo",
            LabelEN = "Raven",
        },
        Serpiente = {
            Image   = "rbxassetid://98063936561193",
            LabelES = "Serpiente",
            LabelEN = "Serpent",
        },
        Arana = {
            Image   = "rbxassetid://71613096970405",
            LabelES = "Araña",
            LabelEN = "Spider",
        },
        Murcielago = {
            Image   = "rbxassetid://81944295677499",
            LabelES = "Murciélago",
            LabelEN = "Bat",
        },
        Sapo = {
            Image   = "rbxassetid://93406897671652",
            LabelES = "Sapo",
            LabelEN = "Toad",
        },
        Pino = {
            Image   = "rbxassetid://96266964258524",
            LabelES = "Pino",
            LabelEN = "Pine",
        },
        Roble = {
            Image   = "rbxassetid://87361999965646",
            LabelES = "Roble",
            LabelEN = "Oak",
        },
        Bambu = {
            Image   = "rbxassetid://87702422458743",
            LabelES = "Bambú",
            LabelEN = "Bamboo",
        },
        Cactus = {
            Image   = "rbxassetid://140359909738061",
            LabelES = "Cactus",
            LabelEN = "Cactus",
        },
        Hongo = {
            Image   = "rbxassetid://88699407088396",
            LabelES = "Hongo",
            LabelEN = "Mushroom",
        },
        Flor = {
            Image   = "rbxassetid://107422008803171",
            LabelES = "Flor",
            LabelEN = "Flower",
        },
        Rosa = {
            Image   = "rbxassetid://118349874792415",
            LabelES = "Rosa",
            LabelEN = "Rose",
        },
        Girasol = {
            Image   = "rbxassetid://81951697702560",
            LabelES = "Girasol",
            LabelEN = "Sunflower",
        },
        Lirio = {
            Image   = "rbxassetid://92841209661864",
            LabelES = "Lirio",
            LabelEN = "Lily",
        },
        Trebol = {
            Image   = "rbxassetid://119551155164964",
            LabelES = "Trébol",
            LabelEN = "Clover",
        },
        Hoja = {
            Image   = "rbxassetid://89362207418148",
            LabelES = "Hoja",
            LabelEN = "Leaf",
        },
        Semilla = {
            Image   = "rbxassetid://74403918116479",
            LabelES = "Semilla",
            LabelEN = "Seed",
        },
        Raiz = {
            Image   = "rbxassetid://140125987348949",
            LabelES = "Raíz",
            LabelEN = "Root",
        },
        Fruto = {
            Image   = "rbxassetid://111312562670718",
            LabelES = "Fruto",
            LabelEN = "Fruit",
        },
        Manzana = {
            Image   = "rbxassetid://115470600107675",
            LabelES = "Manzana",
            LabelEN = "Apple",
        },
        Limon = {
            Image   = "rbxassetid://70729266322417",
            LabelES = "Limón",
            LabelEN = "Lemon",
        },
        Cereza = {
            Image   = "rbxassetid://80352560380837",
            LabelES = "Cereza",
            LabelEN = "Cherry",
        },
        Uva = {
            Image   = "rbxassetid://76848216198474",
            LabelES = "Uva",
            LabelEN = "Grape",
        },
        Sandia = {
            Image   = "rbxassetid://76077309844055",
            LabelES = "Sandía",
            LabelEN = "Watermelon",
        },
        Pera = {
            Image   = "rbxassetid://138349702645758",
            LabelES = "Pera",
            LabelEN = "Pear",
        },
        Durazno = {
            Image   = "rbxassetid://117140632487643",
            LabelES = "Durazno",
            LabelEN = "Peach",
        },
        Platano = {
            Image   = "rbxassetid://94554111028859",
            LabelES = "Plátano",
            LabelEN = "Banana",
        },
        Coco = {
            Image   = "rbxassetid://75197841533660",
            LabelES = "Coco",
            LabelEN = "Coconut",
        },
        Pina = {
            Image   = "rbxassetid://124483121185336",
            LabelES = "Piña",
            LabelEN = "Pineapple",
        },
        Fresa = {
            Image   = "rbxassetid://97207753366791",
            LabelES = "Fresa",
            LabelEN = "Strawberry",
        },
        Zanahoria = {
            Image   = "rbxassetid://98954600210503",
            LabelES = "Zanahoria",
            LabelEN = "Carrot",
        },
        Maiz = {
            Image   = "rbxassetid://135149316177283",
            LabelES = "Maíz",
            LabelEN = "Corn",
        },
        Calabaza = {
            Image   = "rbxassetid://85091944649511",
            LabelES = "Calabaza",
            LabelEN = "Pumpkin",
        },
        Berenjena = {
            Image   = "rbxassetid://80882422845734",
            LabelES = "Berenjena",
            LabelEN = "Eggplant",
        },
        Chile = {
            Image   = "rbxassetid://79535384120015",
            LabelES = "Chile",
            LabelEN = "Chili",
        },
        Brocoli = {
            Image   = "rbxassetid://74544879645621",
            LabelES = "Brócoli",
            LabelEN = "Broccoli",
        },
        Lechuga = {
            Image   = "rbxassetid://88531960884665",
            LabelES = "Lechuga",
            LabelEN = "Lettuce",
        },
        Tomate = {
            Image   = "rbxassetid://75639892753595",
            LabelES = "Tomate",
            LabelEN = "Tomato",
        },
        Pepino = {
            Image   = "rbxassetid://75274553646328",
            LabelES = "Pepino",
            LabelEN = "Cucumber",
        },
        Aguacate = {
            Image   = "rbxassetid://117263520198912",
            LabelES = "Aguacate",
            LabelEN = "Avocado",
        },
        Lirio2 = {
            Image   = "rbxassetid://134535455079374",
            LabelES = "Lirio2",
            LabelEN = "Lily2",
        },
        Jazmin = {
            Image   = "rbxassetid://133491764169252",
            LabelES = "Jazmín",
            LabelEN = "Jasmine",
        },
        Perro = {
            Image   = "rbxassetid://136398966598623",
            LabelES = "Perro",
            LabelEN = "Dog",
        },
        Gato = {
            Image   = "rbxassetid://132779557907183",
            LabelES = "Gato",
            LabelEN = "Cat",
        },
        Conejo = {
            Image   = "rbxassetid://125634784891081",
            LabelES = "Conejo",
            LabelEN = "Rabbit",
        },
        Hamster = {
            Image   = "rbxassetid://118462422909827",
            LabelES = "Hámster",
            LabelEN = "Hamster",
        },
        Raton = {
            Image   = "rbxassetid://85559966504646",
            LabelES = "Ratón",
            LabelEN = "Mouse",
        },
        Ardilla = {
            Image   = "rbxassetid://82041298898466",
            LabelES = "Ardilla",
            LabelEN = "Squirrel",
        },
        Zorro = {
            Image   = "rbxassetid://92280192758955",
            LabelES = "Zorro",
            LabelEN = "Fox",
        },
        Oso = {
            Image   = "rbxassetid://136173352335125",
            LabelES = "Oso",
            LabelEN = "Bear",
        },
        Panda = {
            Image   = "rbxassetid://81500878734148",
            LabelES = "Panda",
            LabelEN = "Panda",
        },
        Koala = {
            Image   = "rbxassetid://80987588016823",
            LabelES = "Koala",
            LabelEN = "Koala",
        },
        Canguro = {
            Image   = "rbxassetid://119766728277257",
            LabelES = "Canguro",
            LabelEN = "Kangaroo",
        },
        Elefante = {
            Image   = "rbxassetid://107491493080178",
            LabelES = "Elefante",
            LabelEN = "Elephant",
        },
        Jirafa = {
            Image   = "rbxassetid://87524244501507",
            LabelES = "Jirafa",
            LabelEN = "Giraffe",
        },
        Cebra = {
            Image   = "rbxassetid://121991543617003",
            LabelES = "Cebra",
            LabelEN = "Zebra",
        },
        Leon = {
            Image   = "rbxassetid://80483467061143",
            LabelES = "León",
            LabelEN = "Lion",
        },
        Tigre = {
            Image   = "rbxassetid://77251880329927",
            LabelES = "Tigre",
            LabelEN = "Tiger",
        },
        Leopardo = {
            Image   = "rbxassetid://104992269284093",
            LabelES = "Leopardo",
            LabelEN = "Leopard",
        },
        Hipopotamo = {
            Image   = "rbxassetid://86638706276550",
            LabelES = "Hipopótamo",
            LabelEN = "Hippo",
        },
        Rinoceronte = {
            Image   = "rbxassetid://133759270431185",
            LabelES = "Rinoceronte",
            LabelEN = "Rhino",
        },
        Gorila = {
            Image   = "rbxassetid://70483509368281",
            LabelES = "Gorila",
            LabelEN = "Gorilla",
        },
        Mono = {
            Image   = "rbxassetid://82970284949153",
            LabelES = "Mono",
            LabelEN = "Monkey",
        },
        Pinguino = {
            Image   = "rbxassetid://90826561109383",
            LabelES = "Pingüino",
            LabelEN = "Penguin",
        },
        Buho = {
            Image   = "rbxassetid://127827669684663",
            LabelES = "Búho",
            LabelEN = "Owl",
        },
        Aguila = {
            Image   = "rbxassetid://121470613063480",
            LabelES = "Águila",
            LabelEN = "Eagle",
        },
        Loro = {
            Image   = "rbxassetid://74862724942328",
            LabelES = "Loro",
            LabelEN = "Parrot",
        },
        Flamenco = {
            Image   = "rbxassetid://71941021312193",
            LabelES = "Flamenco",
            LabelEN = "Flamingo",
        },
        Pavo = {
            Image   = "rbxassetid://79633711484014",
            LabelES = "Pavo",
            LabelEN = "Peacock",
        },
        Paloma = {
            Image   = "rbxassetid://85767551285064",
            LabelES = "Paloma",
            LabelEN = "Dove",
        },
        Colibri = {
            Image   = "rbxassetid://79894057717217",
            LabelES = "Colibrí",
            LabelEN = "Hummingbird",
        },
        Pelicano = {
            Image   = "rbxassetid://102593930579075",
            LabelES = "Pelícano",
            LabelEN = "Pelican",
        },
        Cocodrilo = {
            Image   = "rbxassetid://117142436319014",
            LabelES = "Cocodrilo",
            LabelEN = "Crocodile",
        },
        Iguana = {
            Image   = "rbxassetid://97338949788570",
            LabelES = "Iguana",
            LabelEN = "Iguana",
        },
        Camaleon = {
            Image   = "rbxassetid://80410372953878",
            LabelES = "Camaleón",
            LabelEN = "Chameleon",
        },
        Gecko = {
            Image   = "rbxassetid://89773400163064",
            LabelES = "Gecko",
            LabelEN = "Gecko",
        },
        Rana = {
            Image   = "rbxassetid://125803302958872",
            LabelES = "Rana",
            LabelEN = "Frog",
        },
        Axolotl = {
            Image   = "rbxassetid://126548180481486",
            LabelES = "Axolotl",
            LabelEN = "Axolotl",
        },
        Caballo = {
            Image   = "rbxassetid://87765091931082",
            LabelES = "Caballo",
            LabelEN = "Horse",
        },
        Burro = {
            Image   = "rbxassetid://82715664960054",
            LabelES = "Burro",
            LabelEN = "Donkey",
        },
        Vaca = {
            Image   = "rbxassetid://136167343312191",
            LabelES = "Vaca",
            LabelEN = "Cow",
        },
        Toro = {
            Image   = "rbxassetid://139941775731250",
            LabelES = "Toro",
            LabelEN = "Bull",
        },
        Oveja = {
            Image   = "rbxassetid://110075311319906",
            LabelES = "Oveja",
            LabelEN = "Sheep",
        },
        Cabra = {
            Image   = "rbxassetid://122569910930979",
            LabelES = "Cabra",
            LabelEN = "Goat",
        },
        Cerdo = {
            Image   = "rbxassetid://102459512680107",
            LabelES = "Cerdo",
            LabelEN = "Pig",
        },
        Gallina = {
            Image   = "rbxassetid://121215575117903",
            LabelES = "Gallina",
            LabelEN = "Hen",
        },
        Gallo = {
            Image   = "rbxassetid://121436658554933",
            LabelES = "Gallo",
            LabelEN = "Rooster",
        },
        Pato = {
            Image   = "rbxassetid://96088760864957",
            LabelES = "Pato",
            LabelEN = "Duck",
        },
        Ganso = {
            Image   = "rbxassetid://131651539603356",
            LabelES = "Ganso",
            LabelEN = "Goose",
        },
        Camello = {
            Image   = "rbxassetid://112346281053245",
            LabelES = "Camello",
            LabelEN = "Camel",
        },
        Llama = {
            Image   = "rbxassetid://129874528310662",
            LabelES = "Llama",
            LabelEN = "Llama",
        },
        Alpaca = {
            Image   = "rbxassetid://90556703473815",
            LabelES = "Alpaca",
            LabelEN = "Alpaca",
        },
        Ciervo = {
            Image   = "rbxassetid://117987188552403",
            LabelES = "Ciervo",
            LabelEN = "Deer",
        },
        Alce = {
            Image   = "rbxassetid://74091281368050",
            LabelES = "Alce",
            LabelEN = "Moose",
        },
        Bisonte = {
            Image   = "rbxassetid://106496722412111",
            LabelES = "Bisonte",
            LabelEN = "Bison",
        },
        Nutria = {
            Image   = "rbxassetid://102372602580762",
            LabelES = "Nutria",
            LabelEN = "Otter",
        },
        Castor = {
            Image   = "rbxassetid://119483919929141",
            LabelES = "Castor",
            LabelEN = "Beaver",
        },
        Mapache = {
            Image   = "rbxassetid://86837324762030",
            LabelES = "Mapache",
            LabelEN = "Raccoon",
        },
        Mofeta = {
            Image   = "rbxassetid://82387328094878",
            LabelES = "Mofeta",
            LabelEN = "Skunk",
        },
        Coyote = {
            Image   = "rbxassetid://113054280401952",
            LabelES = "Coyote",
            LabelEN = "Coyote",
        },
        Hiena = {
            Image   = "rbxassetid://126757679196469",
            LabelES = "Hiena",
            LabelEN = "Hyena",
        },
        Suricata = {
            Image   = "rbxassetid://122238881308737",
            LabelES = "Suricata",
            LabelEN = "Meerkat",
        },
        Wombat = {
            Image   = "rbxassetid://114838786308185",
            LabelES = "Wombat",
            LabelEN = "Wombat",
        },
        Tapir = {
            Image   = "rbxassetid://121521571666273",
            LabelES = "Tapir",
            LabelEN = "Tapir",
        },
        Capibara = {
            Image   = "rbxassetid://120424737173557",
            LabelES = "Capibara",
            LabelEN = "Capybara",
        },
        Armadillo = {
            Image   = "rbxassetid://139421545839286",
            LabelES = "Armadillo",
            LabelEN = "Armadillo",
        },
        Topo = {
            Image   = "rbxassetid://95974116741413",
            LabelES = "Topo",
            LabelEN = "Mole",
        },
        Erizo = {
            Image   = "rbxassetid://124804098881998",
            LabelES = "Erizo",
            LabelEN = "Hedgehog",
        },
        Muflon = {
            Image   = "rbxassetid://114664314690391",
            LabelES = "Muflón",
            LabelEN = "Mouflon",
        },
        Bufalo = {
            Image   = "rbxassetid://112836562981233",
            LabelES = "Búfalo",
            LabelEN = "Buffalo",
        },
        Antilope = {
            Image   = "rbxassetid://117834684297977",
            LabelES = "Antílope",
            LabelEN = "Antelope",
        },
        Ornitorrinco = {
            Image   = "rbxassetid://110607168845236",
            LabelES = "Ornitorrinco",
            LabelEN = "Platypus",
        },
        Puercoespin = {
            Image   = "rbxassetid://77794443086564",
            LabelES = "Puercoespín",
            LabelEN = "Porcupine",
        },
        Mangosta = {
            Image   = "rbxassetid://130385352984972",
            LabelES = "Mangosta",
            LabelEN = "Mongoose",
        },
        Turon = {
            Image   = "rbxassetid://79596537485559",
            LabelES = "Turón",
            LabelEN = "Polecat",
        },
        Huron = {
            Image   = "rbxassetid://120035426955566",
            LabelES = "Hurón",
            LabelEN = "Ferret",
        },
        Civeta = {
            Image   = "rbxassetid://127525129216482",
            LabelES = "Civeta",
            LabelEN = "Civet",
        },
        Binturong = {
            Image   = "rbxassetid://121093476438810",
            LabelES = "Binturong",
            LabelEN = "Binturong",
        },
    }
}
